{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"  
data:
{{- range .Values.configmap.envs }}
  {{- .name | nindent 2 }}: {{ .value | quote }}
{{- end }}
{{- end }}
