{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"  
type: Opaque
data:
{{- range .Values.secret.envs }}
  {{- .name | nindent 2 }}: {{ .value  | b64enc }}
{{- end }}
{{- end }}
