ingress:
  enabled: true
  class: alb
  lbName: alb-betdeep-prd
  groupName: betdeep-prd
  hosts:
    - host: cms.betdeep.net
      paths:
        - path: /
          serviceName: betdeep-cms-strapi

hpa:
  minReplicas: 2
  maxReplicas: 20

nodeSelector:
  tier: app

