ingress:
  enabled: true
  class: alb
  lbName: alb-betdeep-dev
  groupName: betdeep-dev
  hosts:
    - host: dev-cms.betdeep.net
      paths:
        - path: /
          serviceName: betdeep-cms-strapi
hpa:
  minReplicas: 1
  maxReplicas: 4

nodeSelector:
  tier: app
