ingress:
  enabled: true
  class: external
  hosts:
    - host: dev-cms.betdeep.net
      paths:
        - path: /
          serviceName: betdeep-cms-strapi
hpa:
  minReplicas: 1
  maxReplicas: 4

nodeSelector:
  tier: develop
