replicaCount: 2

image:
  name: 701128946362.dkr.ecr.ap-southeast-1.amazonaws.com/betdeep-cms-strapi
  tag: 'latest'

name: 'betdeep-cms-strapi'

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

configmap:
  enabled: false

secret:
  enabled: false

secret_extarnal:
  enabled: true

tolerations: []

affinity: {}
