name: Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "production-sc99-cms-strapi"
          heroku_email: "sctechthailand@gmail.com"
          branch: "main"
          remote_branch: "main"
